# Generated by Django 4.2.4 on 2023-08-18 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_blogtittle_blog_blogtitle_alter_blog_blogdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 12, 20, 53, 206229, tzinfo=datetime.timezone.utc)),
        ),
    ]
